[sniffer]
file_path = "../test/samples/100subframes_Matlab_generated_RNTI_12345_scramblingID_1131_cid_123_rxsample23040000_20MHz.fc32"
sample_rate = 23040000
frequency = 627750000

[[pdcch]]
use_config_from_mib = false
si_dci_only = false
rnti_start = 12345
rnti_end = 12345
scrambling_id_start = 1131
scrambling_id_end = 1131
dci_sizes_list = [37, 39, 41]
